### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by hdoria** [hohl/MIHCrypto#39]
Any plans for Carthage support?

**Comment by hohl** [comment]
I'm not using it myself. However I guess it shouldn't be that different from CocoaPods. I'll have a look at in the next days.

**Comment by hohl** [comment]
I just spend some time in reading into Carthage and it looks like a nice tool, but quite different to CocoaPods. And so is the creation of the required files. Since I'm not (yet) using Carthage, I don't want to spend much time on creating support for it, I'm sorry.

But if you've got experience with creating Carthage frameworks, you're free to fork the repo, add support for it and send me a push-request, which I'd happily accept.
