### ISSUE TITLE
Any plan to support OSX 10.11？

### ISSUE THREAD

**Issue by FongRay** [hohl/MIHCrypto#47]
Hi，i got many warnings with XCode 7 & OSX 10.11

![qq20160920-0](https://cloud.githubusercontent.com/assets/5010519/18655925/4aaf93f0-7f1f-11e6-9328-cf5585e7236e.png)

so how can i do RSA encrypt in OSX 10.11 El Capitan？

**Comment by hohl** [comment]
How did you import the MIHCrypto project? This doesn't look like you installed it via CocoaPods? 

These errors you're seeing telling you, that the OpenSSL version which has been build into OS X and iOS is deprecated and should not get used anymore. That's why MIHCrypto ships with an own up-to-date copy of OpenSSL which then gets bundled to your app when you ship it.

However, if you for example just copy the MIHCrypto sources into your project, you need to manually build an up-to-date copy of OpenSSL and link it to your project. This is the reason why using CocoaPods is the recommended way of using MIHCrypto, because it does all that already for you.

**Comment by FongRay** [comment]
@hohl Thanks! I copy the source just as you said, so i can solve it!
