### ISSUE TITLE
How do I initialize MIHRSAPublicKey using the public key string returned by the server?

### ISSUE THREAD

**Issue by Kejiasir** [hohl/MIHCrypto#53]
@hohl  hey!  my server returns a public key string that needs to be decrypted through it, but it crashes when it is initialized by the following method

``` objc
// The public key string returned by the Java server                
// MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCsD2JQlxPCHm1+g1faPDKAdf9bOL4DmeO2YRdT/UCAGESXortYb7TyPtUI9s3gQZG3QsgP1Op59OlVTqrIbeUJ0rHl1q3As7Tm064IuaVL2ocvIkIW2Dx5bSqA2wKwvoRs7O0cAFxspDA8xZesp8DRNZ28LQdF/s8+TMQYecOcGQIDAQAB

NSString *webPublicKey = [self getTokenInfo].rsaPublicKey;
NSData *publicData = [webPublicKey dataUsingEncoding:NSUTF8StringEncoding];
MIHRSAPublicKey *rsaPublicKey = [[MIHRSAPublicKey alloc] initWithData:publicData];
```
![qq20170914-100354](https://user-images.githubusercontent.com/14361443/30408882-3e4166d6-9934-11e7-981c-9fd5d42cdb45.png)

Hope to get your help, be grateful, wish you a happy life

**Comment by Kejiasir** [comment]
Oh, I found a solution, thank you

**Comment by hohl** [comment]
`initWithData` expects the binary data not a BASE64 encoded string of the data. But there is a helper included `NSData *publicKeyData = [yourPublicKeyString MIH_dataByBase64DecodingString]`. However, you don't even need that helper anymore since In more recent iOS and macOS versions a base64 encoding helper is included on the `NSString` class already.
