### ISSUE TITLE
cannot find the newest version(0.5.0) in pod

### ISSUE THREAD

**Issue by zty0** [hohl/MIHCrypto#62]
@hohl hello, do you forget to publish the newest version of this library to center repo of cocoapods?

**Comment by hohl** [comment]
No, I did not forget to upload it there. But uploading it in its current form is not possible, as (since changes in CocoaPods 1.0) the linting of the library fails and I (and some supporters) could not figure out a way to get it linited while still relying on the OpenSSL library as a dependency.

Best way to use the library right now is to load it directly from this repo (and maybe fix it to a commit):

```
pod 'MIHCrypto', :git => 'https://github.com/hohl/MIHCrypto.git'
```

**Comment by zty0** [comment]
oh, Ok. that's unfortunate. I'll load it directly from this repo, thanks.
